# Documentation: https://rmk.rs/docs/configuration.html

[keyboard]
name = "Darshan_Test"
product_name = "Darshan_Test"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Darshan"
chip = "esp32c3"

[matrix]
row_pins = ["GPIO5"]
col_pins = ["GPIO6"]

[layout]
rows = 1
cols = 1
layers = 1

keymap = [
    [
        ["A"]
    ]
]
